/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdada",
        "legal-blue": "#428bff",
        ink: "#222222",
        "on-surface-variant": "#5c3f41",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-on-surface": "#ffedec",
        "inverse-surface": "#3f2b2c",
        "on-primary-fixed": "#40000d",
        canvas: "#ffffff",
        "primary-container": "#e21e4a",
        "on-error-container": "#93000a",
        "on-surface": "#281718",
        "on-primary-container": "#fffbff",
        "on-tertiary-container": "#f6fff6",
        "rausch-active": "#e00b41",
        "error-container": "#ffdad6",
        "surface-container-highest": "#fbdbdc",
        muted: "#6a6a6a",
        "hairline-soft": "#ebebeb",
        "on-background": "#281718",
        "on-tertiary-fixed-variant": "#005234",
        "surface-tint": "#be0038",
        "tertiary-container": "#008558",
        "surface-strong": "#f2f2f2",
        "on-primary-fixed-variant": "#920029",
        "rausch-disabled": "#ffd1da",
        primary: "#ba0036",
        "surface-container-low": "#fff0f0",
        "muted-soft": "#929292",
        "surface-container-lowest": "#ffffff",
        secondary: "#5f5e5e",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#62dca3",
        background: "#fff8f7",
        hairline: "#dddddd",
        "surface-soft": "#f7f7f7",
        "plus-magenta": "#92174d",
        rausch: "#ff385c",
        scrim: "rgba(0,0,0,0.5)",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        body: "#3f3f3f",
        surface: "#fff8f7",
        "tertiary-fixed": "#80f9bd",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#e5bdbe",
        tertiary: "#006a45",
        "surface-dim": "#f2d3d3",
        "surface-variant": "#fbdbdc",
        outline: "#906f70",
        "luxe-purple": "#460479",
        error: "#c13515",
        "surface-bright": "#fff8f7",
        "on-secondary-container": "#636262",
        "primary-fixed-dim": "#ffb2b6",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb2b6",
        "surface-container": "#ffe9e9",
        "border-strong": "#c1c1c1",
        "surface-container-high": "#ffe1e2",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed": "#1b1c1c"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        sm: "8px",
        md: "12px",
        xxl: "48px",
        xxs: "2px",
        section: "64px",
        base: "16px",
        xl: "32px",
        lg: "24px",
        xs: "4px"
      },
      fontFamily: {
        "nav-link": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        caption: ["Plus Jakarta Sans", "sans-serif"],
        "uppercase-tag": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-xl": ["Plus Jakarta Sans", "sans-serif"],
        "rating-display": ["Plus Jakarta Sans", "sans-serif"],
        badge: ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "nav-link": ["16px", { lineHeight: "1.25", letterSpacing: "0", fontWeight: "600" }],
        caption: ["14px", { lineHeight: "1.29", letterSpacing: "0" }],
        "body-sm": ["14px", { lineHeight: "1.43", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0" }],
        "title-md": ["16px", { lineHeight: "1.25", letterSpacing: "0", fontWeight: "600" }],
        "display-lg": ["22px", { lineHeight: "1.18", letterSpacing: "-0.44px", fontWeight: "500" }],
        "display-md": ["21px", { lineHeight: "1.43", letterSpacing: "0", fontWeight: "700" }],
        "display-xl": ["28px", { lineHeight: "1.43", letterSpacing: "0", fontWeight: "700" }],
        badge: ["11px", { lineHeight: "1.18", letterSpacing: "0", fontWeight: "600" }],
        "uppercase-tag": ["8px", { lineHeight: "1.25", letterSpacing: "0.32px", fontWeight: "700" }]
      }
    }
  },
  plugins: []
};
