/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/airports/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Typeahead search for airports.
         * @description Ranks results across multiple match tiers (exact code → code prefix →
         *     city prefix → city substring → fuzzy/trigram on city), returning up to
         *     `limit` results sorted by tier, then alphabetically by city. Fuzzy
         *     tier only fires for queries of length ≥ 3.
         *
         *     An empty/whitespace `q` returns the top `limit` airports alphabetically
         *     by city — used to populate the typeahead dropdown on input focus.
         */
        get: operations["searchAirports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flights/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search for flight itineraries (one-way).
         * @description Returns a paginated, sorted list of itineraries from `origin` to
         *     `destination` on `departureDate`. An itinerary may be direct or
         *     include up to `filters.maxStopovers` connections (system hard cap: 2).
         *
         *     The server computes the top-200 matches for the
         *     `(route, date, filters, sortBy)` tuple, caches them, and slices
         *     `page`/`pageSize` from that cache. `totalResults` reflects the size
         *     of the cached top-K, not the total count of all possible matches in
         *     the database.
         *
         *     When `filters.fareClasses` is empty or omitted, each itinerary is
         *     priced at its cheapest available class; the row's `fareClass` field
         *     identifies which class produced that price. When `fareClasses` is
         *     set, itineraries are filtered to those offering at least one of the
         *     requested classes and priced at the cheapest of those.
         *
         *     Sort mode `durationAsc` orders by **total trip time** (first leg
         *     depart → last leg arrive), not by sum of flight times.
         */
        post: operations["searchFlights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a booking (single passenger, one or more legs).
         * @description Atomically inserts one `bookings` row, one `tickets` row, and one
         *     `segments` row per leg, then returns the persisted booking. All
         *     prices are recomputed server-side from
         *     `route_fares × airplane_price_factor` for the leg's fare class —
         *     the request does not carry prices.
         *
         *     Multi-passenger bookings are a future slice. This endpoint accepts
         *     exactly one passenger; `tickets.outbound` is set to `true` for the
         *     single ticket created (round-trip search is also future work, so
         *     the outbound/return split is not yet exposed).
         *
         *     **Concurrency.** The unique constraint
         *     `segments (flight_id, seat_no)` is the only seat-locking mechanism
         *     in this slice: concurrent bookings of the same seat race to the
         *     first INSERT; the loser receives a `409` with a list of seats that
         *     clashed and is expected to refetch the seat map and repick. A
         *     soft-hold table (`seat_holds`) is a planned follow-up.
         *
         *     **Payment.** Card details are validated for format and discarded.
         *     They are not transmitted, persisted, or processed.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flights/{flightId}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seat map for a specific flight.
         * @description Returns the airframe, the cabin layout (column letters and aisle
         *     positions), and every seat on the aircraft for the given flight,
         *     with each seat marked `unavailable: true` if it has already been
         *     booked. Each seat carries the price for its fare class on this
         *     flight, computed the same way as flight search
         *     (`route_fares.price × airplane_price_factor`).
         *
         *     Seats in fare classes that are not sold on this route (no matching
         *     `route_fares` row) are omitted from the response entirely — they
         *     physically exist on the airframe but cannot be booked for this
         *     flight.
         *
         *     Refuses with `409` for flights in a status that does not allow seat
         *     selection (anything other than `Scheduled`, `On Time`, `Delayed`,
         *     `Boarding`).
         */
        get: operations["getSeatMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Minimal airport representation for typeahead and selection UIs. */
        AirportSummary: {
            /**
             * @description IATA airport code.
             * @example LHR
             */
            airportCode: string;
            /**
             * @description City name.
             * @example London
             */
            city: string;
        };
        /** @description Search parameters and filters for flight itinerary lookup. */
        FlightSearchRequest: {
            /**
             * @description IATA code of the origin airport.
             * @example LHR
             */
            origin: string;
            /**
             * @description IATA code of the destination airport.
             * @example JFK
             */
            destination: string;
            /**
             * Format: date
             * @description Calendar date of departure at the origin airport (local).
             * @example 2026-06-15
             */
            departureDate: string;
            /** @default 1 */
            passengerCount: number;
            sortBy?: components["schemas"]["SortBy"];
            /**
             * @description Zero-based page index.
             * @default 0
             */
            page: number;
            /** @default 20 */
            pageSize: number;
            filters?: components["schemas"]["FlightSearchFilters"];
        };
        /**
         * @description All filters are optional. Omitted filters and default-valued filters
         *     are excluded from the server cache key, so wide-open searches share
         *     cache entries.
         */
        FlightSearchFilters: {
            priceRange?: components["schemas"]["PriceRange"];
            /** @description Empty/omitted = all classes allowed. */
            fareClasses?: components["schemas"]["FareClass"][];
            departureMinutesRange?: components["schemas"]["MinuteRange"];
            arrivalMinutesRange?: components["schemas"]["MinuteRange"];
            /**
             * @description System hard cap is 2.
             * @default 2
             */
            maxStopovers: number;
            /**
             * @description Maximum total trip time (first leg depart → last leg arrive).
             *     Omitted = no cap.
             */
            maxTotalTravelTimeHours?: number;
        };
        /** @description Inclusive price range in the response currency. */
        PriceRange: {
            min: number;
            max: number;
        };
        /** @description Time-of-day range expressed as minutes since midnight (0–1439). */
        MinuteRange: {
            min: number;
            max: number;
        };
        /** @enum {string} */
        FareClass: "Economy" | "Comfort" | "Business";
        /**
         * @description Result ordering. `durationAsc` is **total trip time** ascending,
         *     not sum of flight times.
         * @default priceAsc
         * @enum {string}
         */
        SortBy: "priceAsc" | "priceDesc" | "durationAsc" | "departureAsc";
        /** @description One page of search results. */
        FlightSearchResponse: {
            page: number;
            pageSize: number;
            /**
             * @description Size of the cached top-K result set (≤ 200). May be smaller than
             *     200 if fewer itineraries matched. Not the total count of all
             *     possible matches in the database.
             */
            totalResults: number;
            totalPages: number;
            results: components["schemas"]["Itinerary"][];
        };
        /**
         * @description A sequence of one or more flight legs from origin to destination,
         *     priced at a single fare class.
         */
        Itinerary: {
            /**
             * @description Stable identifier within the cached result set (deterministic
             *     hash of leg sequence + fare class). Not durable across cache
             *     evictions.
             */
            id: string;
            fareClass: components["schemas"]["FareClass"];
            /** @description Total price for one passenger at `fareClass`. */
            price: number;
            /**
             * @default USD
             * @example USD
             */
            currency: string;
            /** @description First leg's departure → last leg's arrival. */
            totalTripTimeMinutes: number;
            /** @description Sum of leg durations. Excludes layovers. */
            flightTimeMinutes: number;
            totalLayoverMinutes: number;
            /** @description Number of intermediate airports (`legs.length - 1`). */
            stopovers: number;
            legs: components["schemas"]["Leg"][];
        };
        /** @description One flight segment within an itinerary. */
        Leg: {
            /**
             * @description Durable identifier of the underlying `bookings.flights` row.
             *     Used by the seat-map endpoint (`/flights/{flightId}/seats`).
             */
            flightId: number;
            /** @example BA178 */
            flightNumber: string;
            fromAirport: components["schemas"]["AirportSummary"];
            toAirport: components["schemas"]["AirportSummary"];
            /**
             * Format: date-time
             * @description UTC instant of scheduled departure.
             */
            departureAt: string;
            /**
             * Format: date-time
             * @description UTC instant of scheduled arrival.
             */
            arrivalAt: string;
            durationMinutes: number;
            /**
             * @description True when arrival lands on a later calendar day than departure
             *     in the destination airport's local timezone. UI convenience.
             */
            nextDayArrival: boolean;
        };
        /** @description Minimal airframe representation for the seat map. */
        AirplaneSummary: {
            /**
             * @description Airplane code, IATA.
             * @example 32N
             */
            code: string;
            /**
             * @description Airplane model.
             * @example Airbus A320neo
             */
            model: string;
        };
        /**
         * @description Cabin layout for the seat-map renderer. `columns` is the ordered set
         *     of seat-letter columns present on the airframe (derived from the
         *     seats table). `aisles_after` lists the column letters after which
         *     the renderer should draw an aisle gap.
         */
        SeatLayout: {
            /**
             * @example [
             *       "A",
             *       "B",
             *       "C",
             *       "D",
             *       "E",
             *       "F"
             *     ]
             */
            columns: string[];
            /**
             * @description Ordered subset of `columns`. Empty array is valid (renderer
             *     draws no aisle gap).
             * @example [
             *       "C"
             *     ]
             */
            aisles_after: string[];
        };
        /** @description A single seat on the aircraft for this flight. */
        Seat: {
            /**
             * @description Seat identifier, equivalent to `row` concatenated with `letter`.
             * @example 11D
             */
            id: string;
            /** @example 11 */
            row: number;
            /** @example D */
            letter: string;
            seatClass: components["schemas"]["FareClass"];
            /**
             * @description True when the seat is already booked on this flight (a row exists
             *     in `segments` for `(flight_id, seat_no)`). Omitted/false when
             *     free.
             */
            unavailable?: boolean;
            /**
             * @description Price for this seat on this flight, equal to the flight's
             *     per-class price (`route_fares.price × airplane_price_factor`)
             *     for the seat's `seatClass`.
             */
            price: number;
        };
        /** @description Seat map for a specific flight. */
        SeatMapResponse: {
            airplane: components["schemas"]["AirplaneSummary"];
            layout: components["schemas"]["SeatLayout"];
            seats: components["schemas"]["Seat"][];
        };
        /**
         * @description Single-passenger, multi-leg booking. `legs` carries one entry per
         *     flight in the chosen itinerary, in departure order.
         */
        BookingRequest: {
            passenger: components["schemas"]["PassengerInfo"];
            legs: components["schemas"]["BookingLegRequest"][];
            payment: components["schemas"]["MockPayment"];
        };
        BookingLegRequest: {
            flightId: number;
            /** @example 12A */
            seatNo: string;
        };
        PassengerInfo: {
            firstName: string;
            lastName: string;
        };
        /**
         * @description Mock payment details. Validated for format only; never persisted or
         *     sent to a payment processor. The presence of well-formed values
         *     stands in for an actual payment-gateway success.
         */
        MockPayment: {
            /** @description 12–19 digits; spaces tolerated. */
            cardNumber: string;
            /** @example 08/29 */
            expiration: string;
            cvv: string;
        };
        /**
         * @description Confirmation of a completed booking. Mirrors the persisted rows:
         *     one `bookings`, one `tickets`, one `segments` per leg.
         */
        BookingResponse: {
            /**
             * @description Booking reference (6-char uppercase alphanumeric).
             * @example X3F9KQ
             */
            bookRef: string;
            /**
             * Format: date-time
             * @description UTC instant the booking was created.
             */
            bookDate: string;
            /** @description Sum of segment prices. */
            totalAmount: number;
            /**
             * @default USD
             * @example USD
             */
            currency: string;
            passenger: components["schemas"]["PassengerInfo"];
            /**
             * @description Ticket number for the single passenger.
             * @example 0005432900987
             */
            ticketNo: string;
            segments: components["schemas"]["BookedSegment"][];
        };
        /** @description One leg of the confirmed booking, in departure order. */
        BookedSegment: {
            flightId: number;
            /** @example PG0078 */
            flightNumber: string;
            fromAirport: components["schemas"]["AirportSummary"];
            toAirport: components["schemas"]["AirportSummary"];
            /** Format: date-time */
            departureAt: string;
            /** Format: date-time */
            arrivalAt: string;
            fareConditions: components["schemas"]["FareClass"];
            seatNo: string;
            /** @description Server-recomputed price for this segment. */
            price: number;
        };
        /**
         * @description Extension of `Problem` returned (HTTP 409) when one or more
         *     requested seats are no longer available, or a flight in the
         *     request is no longer in a bookable status. `conflicts` enumerates
         *     the per-leg problems so the client can mark and refetch only the
         *     affected legs.
         */
        SeatConflictProblem: components["schemas"]["Problem"] & {
            conflicts: {
                flightId: number;
                /**
                 * @description Seat that clashed (when `reason = seatTaken`). Omitted
                 *     when the conflict is `flightNotBookable`.
                 */
                seatNo?: string;
                /** @enum {string} */
                reason: "seatTaken" | "flightNotBookable";
            }[];
        };
        /**
         * @description RFC 7807 problem details. Returned with `Content-Type: application/problem+json`
         *     for every non-2xx response.
         */
        Problem: {
            /**
             * Format: uri
             * @description URI identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI identifying the specific occurrence (often the request path).
             */
            instance?: string;
        };
        /**
         * @description Extension of `Problem` returned when request validation fails (typically
         *     HTTP 400 or 422). Each entry in `errors` describes one failing field.
         */
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: {
                /** @description Dotted path to the failing field (e.g. `passenger.email`). */
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Request conflicts with the current state of the resource. Used by the
         *     seat-map endpoint when the flight is in a status that does not allow
         *     seat selection (e.g. Departed, Arrived, Cancelled).
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchAirports: {
        parameters: {
            query: {
                /** @description Search text. Empty string is valid (returns top-N). */
                q: string;
                /** @description Maximum number of results. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching airports, possibly empty. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    searchFlights: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlightSearchRequest"];
            };
        };
        responses: {
            /** @description Paginated search results. `results` may be empty. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description Booking created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description One or more `flightId`s do not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description One or more requested seats were taken by another booking
             *     between seat-map load and submit, or a flight in the request
             *     is no longer in a bookable status. `conflicts` enumerates the
             *     per-leg problems.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["SeatConflictProblem"];
                };
            };
        };
    };
    getSeatMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flight ID. */
                flightId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seat map for the flight. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatMapResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
