/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/airports/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Typeahead search for airports.
         * @description Ranks results across multiple match tiers (exact code → code prefix →
         *     city prefix → city substring → fuzzy/trigram on city), returning up to
         *     `limit` results sorted by tier, then alphabetically by city. Fuzzy
         *     tier only fires for queries of length ≥ 3.
         *
         *     An empty/whitespace `q` returns the top `limit` airports alphabetically
         *     by city — used to populate the typeahead dropdown on input focus.
         */
        get: operations["searchAirports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Minimal airport representation for typeahead and selection UIs. */
        AirportSummary: {
            /**
             * @description IATA airport code.
             * @example LHR
             */
            airportCode: string;
            /**
             * @description City name.
             * @example London
             */
            city: string;
        };
        /**
         * @description RFC 7807 problem details. Returned with `Content-Type: application/problem+json`
         *     for every non-2xx response.
         */
        Problem: {
            /**
             * Format: uri
             * @description URI identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description URI identifying the specific occurrence (often the request path).
             */
            instance?: string;
        };
        /**
         * @description Extension of `Problem` returned when request validation fails (typically
         *     HTTP 400 or 422). Each entry in `errors` describes one failing field.
         */
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: {
                /** @description Dotted path to the failing field (e.g. `passenger.email`). */
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchAirports: {
        parameters: {
            query: {
                /** @description Search text. Empty string is valid (returns top-N). */
                q: string;
                /** @description Maximum number of results. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching airports, possibly empty. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
