services:
  postgres:
    image: 'postgres:17'
    container_name: airlines_db
    environment:
      POSTGRES_DB: airlines
      POSTGRES_USER: airlines
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: '--locale=en_US.UTF-8 --encoding=UTF8'
    ports:
      - '5432:5432'
    volumes:
      - airlines_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  airlines_data:
